swagger: '2.0'
info:
  title: Sample API
  version: 1.0.0
paths:
  /authors:
    post:
      summary: Create a new author
      description: |
        Creates a new author with the provided information.
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: author
          description: Author object to be created
          required: true
          schema:
            type: object
            properties:
              name:
                type: string
                description: The name of the author
              email:
                type: string
                format: email
                description: The email address of the author
              bio:
                type: string
                description: A short biography of the author
            required:
              - name
              - email
      responses:
        201:
          description: Author created successfully
          schema:
            type: object
            properties:
              id:
                type: integer
                format: int64
                description: The ID of the newly created author
              name:
                type: string
                description: The name of the author
              email:
                type: string
                format: email
                description: The email address of the author
              bio:
                type: string
                description: A short biography of the author
        400:
          description: Invalid request payload
        500:
          description: Internal server error